# Generated by Django 4.1.3 on 2022-12-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('sucursal', models.CharField(max_length=300)),
                ('unidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=300)),
                ('transporte', models.CharField(max_length=300)),
                ('cantidad_dias', models.IntegerField()),
            ],
        ),
    ]
