# Generated by Django 4.1.3 on 2022-12-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_compras_viajes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='direccion',
            new_name='destino_visitado',
        ),
    ]
